server:
  servlet:
    context-path: /demo
    session:
      timeout: 3600
  port: 9990
  
spring:
  application:
    name: SpringBoot
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
      

#MyBatis配置      
mybatis: 
  type-aliases-package: com.demo
  configuration: 
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  pagehelper: 
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql 